import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    newRecipeFormContainer: {
        width: "100%",
        alignItems: "center",
    },
    textInput: {
        width: "90%",
        height: 50,
        fontSize: 20,
        fontWeight: "bold",
        borderBottomWidth: 3,
        borderBottomColor: "#7542f5",
        marginBottom: 20,
        padding: 10,
        borderRadius: 5,
    },
    textArea: {
        height: 100,
        textAlignVertical: "top",
        borderWidth: 3,
        borderColor: "#7542f5",
        fontSize: 16,
        fontWeight: "normal",
        borderRadius: 5,
    },
    ingredientsContainer: {
        position: "absolute",
        bottom: 0,
        width: "98%",
        height: "99%",
        backgroundColor: "#fff",
        zIndex: 1,
        borderTopRightRadius: 20,
        shadowColor: "#000",
        shadowOffset: {
            width: 10,
            height: 10,
        },
        shadowRadius: 3.84,
        elevation: 5,
        opacity: 0.99,
        shadowOpacity: 0.1,
    },
    stepsContainer: {
        position: "absolute",
        bottom: 0,
        right: 0,
        width: "98%",
        height: "99%",
        backgroundColor: "#fff",
        zIndex: 1,
        borderTopLeftRadius: 20,
        shadowColor: "#000",
        shadowOffset: {
            width: 10,
            height: 10,
        },
        shadowRadius: 3.84,
        elevation: 5,
        opacity: 0.99,
        shadowOpacity: 0.1,
    },
});